-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.congressionalsessions
(
    sessionnumber integer,
    sessionstartedon date,
    sessionendedon date,
    membercount integer,
    nonvoting integer,
    majority character varying COLLATE pg_catalog."default",
    speaker_id character varying COLLATE pg_catalog."default",
    housespeaker character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.housemembers
(
    uniqueid character varying COLLATE pg_catalog."default" NOT NULL,
    govnurl character varying COLLATE pg_catalog."default",
    fullname character varying COLLATE pg_catalog."default",
    firstname character varying COLLATE pg_catalog."default",
    lastname character varying COLLATE pg_catalog."default",
    gender character varying COLLATE pg_catalog."default",
    dob date,
    party character varying COLLATE pg_catalog."default",
    houseterms character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    stateabr character varying COLLATE pg_catalog."default",
    district integer,
    combstatedistrict character varying COLLATE pg_catalog."default",
    statedistid character varying COLLATE pg_catalog."default",
    firstsession character varying COLLATE pg_catalog."default",
    secondsession character varying COLLATE pg_catalog."default",
    thirdsession character varying COLLATE pg_catalog."default",
    congress109 integer,
    congress110 integer,
    congress111 integer,
    congress112 integer,
    congress113 integer,
    congress114 integer,
    congress115 integer,
    congress116 integer,
    congress117 integer,
    congress118 integer,
    CONSTRAINT housemembers_pkey PRIMARY KEY (uniqueid)
);

CREATE TABLE IF NOT EXISTS public.twitterhandles
(
    uniqueid character varying COLLATE pg_catalog."default" NOT NULL,
    fullname character varying COLLATE pg_catalog."default",
    twitterhandle character varying COLLATE pg_catalog."default",
    joinedon date,
    yearjoined integer,
    createdaftersession bit(1),
    yraftertwitter integer,
    CONSTRAINT "TwitterHandles_pkey" PRIMARY KEY (uniqueid)
);

ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress109) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress110) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress111) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress112) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress113) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress114) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress115) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress116) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress117) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.congressionalsessions
    ADD FOREIGN KEY (sessionnumber)
    REFERENCES public.housemembers (congress118) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.housemembers
    ADD FOREIGN KEY (uniqueid)
    REFERENCES public.twitterhandles (uniqueid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.housemembers
    ADD FOREIGN KEY (uniqueid)
    REFERENCES public.congressionalsessions (speaker_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;